# Generated by Django 5.2.5 on 2025-08-19 11:03

import django.db.models.deletion
import repub_interface.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('reviewing', 'Awaiting Review'), ('finalizing', 'Finalizing')], default='pending', max_length=20)),
                ('input_file', models.FileField(blank=True, null=True, upload_to=repub_interface.models.get_upload_path)),
                ('input_type', models.CharField(choices=[('pdf', 'PDF'), ('images', 'Images')], default='images', max_length=10)),
                ('language', models.CharField(default='eng', max_length=100)),
                ('crop', models.BooleanField(default=True)),
                ('deskew', models.BooleanField(default=True)),
                ('ocr', models.BooleanField(default=True)),
                ('dewarp', models.BooleanField(default=False)),
                ('draw_contours', models.BooleanField(default=False)),
                ('gray', models.BooleanField(default=False)),
                ('rotate_type', models.CharField(choices=[('horizontal', 'Horizontal'), ('vertical', 'Vertical'), ('overall', 'Overall')], default='vertical', max_length=20)),
                ('reduce_factor', models.FloatField(blank=True, default='0.2', null=True)),
                ('xmaximum', models.IntegerField(default=30)),
                ('ymax', models.IntegerField(default=60)),
                ('maxcontours', models.IntegerField(default=5)),
                ('output_file', models.FileField(blank=True, null=True, upload_to=repub_interface.models.get_output_path)),
                ('error_message', models.TextField(blank=True)),
                ('needs_review', models.BooleanField(default=False)),
                ('reviewed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processing_jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField()),
                ('original_image', models.CharField(max_length=255)),
                ('cropped_image', models.CharField(blank=True, max_length=255, null=True)),
                ('adjusted_image', models.CharField(blank=True, max_length=255, null=True)),
                ('original_thumbnail', models.ImageField(blank=True, null=True, upload_to=repub_interface.models.get_thumbnail_path)),
                ('cropped_thumbnail', models.ImageField(blank=True, null=True, upload_to=repub_interface.models.get_thumbnail_path)),
                ('auto_crop_box', models.TextField(blank=True, null=True)),
                ('user_crop_box', models.TextField(blank=True, null=True)),
                ('needs_review', models.BooleanField(default=False)),
                ('reviewed', models.BooleanField(default=False)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='repub_interface.processingjob')),
            ],
            options={
                'ordering': ['page_number'],
                'unique_together': {('job', 'page_number')},
            },
        ),
    ]
