# Generated by Django for adding iadir field

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repub_interface', '0002_processingjob_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingjob',
            name='iadir',
            field=models.BooleanField(default=True, help_text='Use Internet Archive directory structure for output'),
        ),
    ]