# Generated by Django 5.2.6 on 2025-10-01 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repub_interface', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingjob',
            name='mingray',
            field=models.IntegerField(default=100),
        ),
    ]
