# Generated by Django 5.2.6 on 2025-11-30 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repub_interface', '0003_processingjob_mingray'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingjob',
            name='derived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processingjob',
            name='derived_identifier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='processingjob',
            name='is_derived',
            field=models.BooleanField(default=False),
        ),
    ]
