# Generated by Django 5.2.6 on 2025-11-30 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repub_interface', '0004_processingjob_derived_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processingjob',
            name='ocr',
            field=models.BooleanField(default=False),
        ),
    ]
