# Generated by Django 5.2.6 on 2025-12-01 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repub_interface', '0005_alter_processingjob_ocr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processingjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('reviewing', 'Awaiting Review'), ('finalizing', 'Finalizing'), ('deriving', 'Deriving'), ('derive_completed', 'Derive Completed'), ('derive_failed', 'Derive Failed')], default='pending', max_length=20),
        ),
    ]
