# Generated by Django 5.2.6 on 2025-12-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repub_interface', '0006_alter_processingjob_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingjob',
            name='identifier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
