# Generated by Django 5.2.6 on 2025-12-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repub_interface', '0007_processingjob_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processingjob',
            name='identifier',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
