# Generated by Django 5.2.6 on 2025-12-14 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repub_interface', '0008_alter_processingjob_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingjob',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
