# Generated by Django 5.2.6 on 2025-12-31 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repub_interface', '0009_processingjob_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingjob',
            name='processing_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
