# Generated by Django 5.2.6 on 2026-02-07 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repub_interface', '0010_processingjob_processing_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingjob',
            name='derive_reduce_factor',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
