# Generated by Django 5.2.6 on 2026-02-07 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repub_interface', '0011_processingjob_derive_reduce_factor'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingjob',
            name='derive_started',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
