# Generated by Django 5.2.6 on 2026-03-26 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repub_interface', '0012_processingjob_derive_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingjob',
            name='correction_notes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='processingjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('reviewing', 'Awaiting Review'), ('finalizing', 'Finalizing'), ('deriving', 'Deriving'), ('derive_completed', 'Derive Completed'), ('derive_failed', 'Derive Failed'), ('under_correction', 'Under Correction')], default='pending', max_length=20),
        ),
    ]
