from django.urls import path
from . import jobs, review, items, directory, users

urlpatterns = [
    path('', jobs.home, name='home'),
    path('jobs/', jobs.all_jobs, name='all_jobs'),
    path('jobs/export-csv/', jobs.export_jobs_csv, name='export_jobs_csv'),
    path('job/<uuid:job_id>/', jobs.job_detail, name='job_detail'),
    path('job/<uuid:job_id>/download/', jobs.job_download, name='job_download'),
    path('job/<uuid:job_id>/finalize/', jobs.finalize_job, name='finalize_job'),
    path('job/<uuid:job_id>/retry/', jobs.retry_job, name='retry_job'),
    path('jobs/bulk-retry/', jobs.bulk_retry_jobs, name='bulk_retry_jobs'),
    path('job/<uuid:job_id>/status/', jobs.job_status, name='job_status'),
    path('job/<uuid:job_id>/stop/', jobs.stop_job, name='stop_job'),
    path('jobs/bulk-stop/', jobs.bulk_stop_jobs, name='bulk_stop_jobs'),
    path('job/<uuid:job_id>/derive/', jobs.derive_job, name='derive_job'),
    path('job/<uuid:job_id>/revert-derive/', jobs.revert_derive, name='revert_derive'),
    path('jobs/bulk-derive/', jobs.bulk_derive_jobs, name='bulk_derive_jobs'),
    path('jobs/bulk-set-derive-failed/', jobs.bulk_set_derive_failed, name='bulk_set_derive_failed'),
    path('job/<uuid:job_id>/cleanup/', jobs.cleanup_job, name='cleanup_job'),
    path('job/<uuid:job_id>/delete/', jobs.delete_job, name='delete_job'),
    path('items/', items.all_items, name='all_items'),
    path('items/export-csv/', items.export_items_csv, name='export_items_csv'),
    path('item/<str:identifier>/delete/', items.delete_item, name='delete_item'),
    path('item/<str:identifier>/', items.item_directory, name='item_directory'),
    path('item/<str:identifier>/<path:subpath>/', items.item_directory, name='item_directory_subpath'),
    path('job/<uuid:job_id>/review/', review.job_review, name='job_review'),
    path('job/<uuid:job_id>/page/<int:pagenum>/', review.page_editor, name='page_editor'),
    path('job/<uuid:job_id>/page/<int:page_number>/save-snip/', review.save_snip, name='save_snip'),
    path('job/<uuid:job_id>/reject-review/', review.reject_review, name='reject_review'),
    path('job/<uuid:job_id>/output-directory/', directory.job_output_directory, name='job_output_directory'),
    path('job/<uuid:job_id>/output-directory/<path:subpath>/', directory.job_output_directory, name='job_output_directory_subpath'),
    path('job/<uuid:job_id>/input-directory/', directory.job_input_directory, name='job_input_directory'),
    path('job/<uuid:job_id>/input-directory/<path:subpath>/', directory.job_input_directory, name='job_input_directory_subpath'),
    path('api/check-identifier/', jobs.check_identifier, name='check_identifier'),
    path('register/', users.register, name='register'),
    path('api-token/', users.api_token_management, name='api_token'),
    path('activate/<str:uidb64>/<str:token>/', users.activate_account, name='activate_account'),
]
