from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('jobs/', views.all_jobs, name='all_jobs'),
    path('jobs/export-csv/', views.export_jobs_csv, name='export_jobs_csv'),
    path('items/', views.all_items, name='all_items'),
    path('items/export-csv/', views.export_items_csv, name='export_items_csv'),
    path('register/', views.register, name='register'),
    path('activate/<str:uidb64>/<str:token>/', views.activate_account, name='activate_account'),
    path('job/<uuid:job_id>/', views.job_detail, name='job_detail'),
    path('job/<uuid:job_id>/download/', views.job_download, name='job_download'),
    path('job/<uuid:job_id>/output-directory/', views.job_output_directory, name='job_output_directory'),
    path('job/<uuid:job_id>/output-directory/<path:subpath>/', views.job_output_directory, name='job_output_directory_subpath'),
    path('job/<uuid:job_id>/input-directory/', views.job_input_directory, name='job_input_directory'),
    path('job/<uuid:job_id>/input-directory/<path:subpath>/', views.job_input_directory, name='job_input_directory_subpath'),
    path('job/<uuid:job_id>/review/', views.job_review, name='job_review'),
    path('job/<uuid:job_id>/page/<int:pagenum>/', views.page_editor, name='page_editor'),
    path('job/<uuid:job_id>/page/<int:page_number>/save-snip/', views.save_snip, name='save_snip'),
    path('job/<uuid:job_id>/finalize/', views.finalize_job, name='finalize_job'),
    path('job/<uuid:job_id>/reject-review/', views.reject_review, name='reject_review'),
    path('job/<uuid:job_id>/retry/', views.retry_job, name='retry_job'),
    path('jobs/bulk-retry/', views.bulk_retry_jobs, name='bulk_retry_jobs'),
    path('job/<uuid:job_id>/status/', views.job_status, name='job_status'),
    path('job/<uuid:job_id>/stop/', views.stop_job, name='stop_job'),
    path('jobs/bulk-stop/', views.bulk_stop_jobs, name='bulk_stop_jobs'),
    path('job/<uuid:job_id>/derive/', views.derive_job, name='derive_job'),
    path('jobs/bulk-derive/', views.bulk_derive_jobs, name='bulk_derive_jobs'),
    path('jobs/bulk-set-derive-failed/', views.bulk_set_derive_failed, name='bulk_set_derive_failed'),
    path('job/<uuid:job_id>/cleanup/', views.cleanup_job, name='cleanup_job'),
    path('job/<uuid:job_id>/delete/', views.delete_job, name='delete_job'),
    path('item/<str:identifier>/delete/', views.delete_item, name='delete_item'),
    path('item/<str:identifier>/', views.item_directory, name='item_directory'),
    path('item/<str:identifier>/<path:subpath>/', views.item_directory, name='item_directory_subpath'),
    path('api-token/', views.api_token_management, name='api_token'),
]
